# Generated by Django 5.0.1 on 2024-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Pno', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('pw', models.CharField(max_length=20)),
            ],
        ),
    ]
