# Generated by Django 5.0.1 on 2024-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='Pno',
            field=models.IntegerField(max_length=10),
        ),
    ]
