# Generated by Django 5.0.1 on 2024-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_data_age_alter_data_pno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='Pno',
            field=models.IntegerField(),
        ),
    ]
